name       : acl
version    : 2.2.52
release    : 11
source     :
    - http://download.savannah.gnu.org/releases/acl/acl-2.2.52.src.tar.gz : 179074bb0580c06c4b4137be4c5a92a701583277967acdb5546043c7874e0d23
license    :
    - LGPL-3.0
summary    : Access control list shared library
component  : system.base
autodep    : no
description: |
    This package contains the libacl.so dynamic library containing the POSIX 1003.1e draft standard 17 functions for manipulating access control lists.
builddeps  :
    - attr-32bit-devel
emul32     : yes
setup      : |
    # Help with musl builds
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %configure --bindir=/bin \
               --libexecdir=%libdir%
build      : |
    %make
install    : |
    %make_install install-lib install-dev DIST_ROOT=$installdir
    rm $installdir/%libdir%/*.la
    %make clean
