name       : acl
version    : 2.2.53
release    : 13
source     :
    - http://download.savannah.nongnu.org/releases/acl/acl-2.2.53.tar.gz : 06be9865c6f418d851ff4494e12406568353b891ffe1f596b34693c387af26c7
license    : LGPL-2.1-only
summary    : Access control list shared library
component  : system.base
autodep    : no
description: |
    This package contains the libacl.so dynamic library containing the POSIX 1003.1e draft standard 17 functions for manipulating access control lists.
builddeps  :
    - pkgconfig32(libattr)
emul32     : yes
environment: |
    # Help with musl builds
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
setup      : |
    %configure --bindir=/bin \
               --libexecdir=%libdir%
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
    %make clean
