name        : acl
version     : 2.2.51
release     : 3
source      :
    - http://download.savannah.gnu.org/releases/acl/acl-2.2.51.src.tar.gz : 06854521cf5d396801af7e54b9636680edf8064355e51c07657ec7442a185225
license     :
    - GPLv3+
summary     : Access control list shared library
description : |
    This package contains the libacl.so dynamic library containing the POSIX 1003.1e draft standard 17 functions for manipulating access control lists.
    
setup      : |
    %configure --disable-static \
               --bindir=/bin \
               --libexecdir=%libdir%
build      : |
    %make
install    : |
    %make_install install-lib install-dev DIST_ROOT=$installdir
    rm $installdir/%libdir%/*.la
