name        : acl
version     : 2.2.51
release     : 7
source      :
    - http://download.savannah.gnu.org/releases/acl/acl-2.2.51.src.tar.gz : 06854521cf5d396801af7e54b9636680edf8064355e51c07657ec7442a185225
license     :
    - LGPL-3.0
summary     : Access control list shared library
autodep     : no
description : |
    This package contains the libacl.so dynamic library containing the POSIX 1003.1e draft standard 17 functions for manipulating access control lists.
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - attr-32bit-devel
emul32     : yes
setup      : |
    %configure --disable-static \
               --bindir=/bin \
               --libexecdir=%libdir%
build      : |
    %make
install    : |
    %make_install install-lib install-dev DIST_ROOT=$installdir
    rm $installdir/%libdir%/*.la
    %make clean
